# Copyright 2013 The Flutter Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
name: vector_math
description: A vector math library for 2D and 3D applications, supporting 2D, 3D, and 4D matrices.
repository: https://github.com/flutter/core-packages/tree/main/packages/vector_math
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+vector_math%22
version: 2.4.2

environment:
  sdk: ^3.10.0

dev_dependencies:
  benchmark_harness: ^2.0.0
  build_runner: ^2.5.0
  build_test: ^3.0.0
  build_web_compilers: ^4.1.1
  path: ^1.9.0
  test: ^1.25.9

topics:
  - math
